@include('user.headh')
@include('user.headerh')


<div class="page-banner-area">
    <div class="container">
    <div class="row align-items-center justify-content-center">
    <div class="col-lg-6 col-md-6">
    <div class="page-banner-content" data-aos="fade-right" data-aos-delay="50" data-aos-duration="500" data-aos-once="true">
    <h2>Terms and Condition</h2>
    <ul>
    <li>
    <a href="{{ route('home') }}">Home</a>
    </li>
    <li>Pages</li>
    <li>Terms and Condition</li>
    </ul>
    </div>
    </div>
    <div class="col-lg-6 col-md-6">
    <div class="page-banner-image" data-aos="fade-left" data-aos-delay="50" data-aos-duration="500" data-aos-once="true">
    <img src="{{ asset('assett/assets/images/page-banner/banner.png') }}" alt="image">
    <div class="banner-shape">
    <img src="{{ asset('assett/assets/images/page-banner/shape.png') }}" alt="image">
    </div>
    </div>
    </div>
    </div>
    </div>
    </div>
    
    
    <div class="terms-of-service-area ptb-100">
    <div class="container">
    <div class="terms-of-service-content">
    <p><i>ATTENTION: YOU MUST BE AT LEAST 18 YEARS OF AGE TO ENTER INTO THIS AGREEMENT AND USE Swiftescrow
    
    .</i></p>
    <h3><span>1.</span> ACCEPTANCE OF TERMS AND CONDITIONS
    </h3>
    <p>Tradeescrow provides Tradeescrow, a collection of online resources, including escrow services for bitcoin transactions (hereinafter, "the Service") subject to the following Terms and Conditions of Use ("Terms and Conditions"), which may be updated by Tradeescrow from time to time. Unless explicitly stated otherwise, any new features that augment or enhance the current Service shall be subject to the Terms and Conditions. Tradeescrow will provide notice of significant changes to the Terms and Conditions by posting notice of said changes on Tradeescrow website. In addition, when using the Service, you shall be subject to any posted guidelines or rules applicable to the Service, which may be posted from time to time. All such guidelines and rules are hereby incorporated by reference into the Terms. By using the Service in any way, you are agreeing to comply with these Terms and Conditions. In order to use the Service, you must obtain access to the World Wide Web, either directly or through devices that access web-based content, and pay any service fees associated with such access. In addition, you must provide all equipment necessary to make such connection to the World Wide Web, including a computer and a modem or other access device. The Service is offered to you conditioned on your acceptance without modification of the terms, conditions, and notices contained herein. Should you object to any part of these Terms and Conditions, any guidelines, or any subsequent modifications thereto or become dissatisfied with Tradeescrow in any way, your only recourse is to immediately discontinue use of Tradeescrow.</p>
    
    <h3><span>2.</span> ONLINE CONTENT</h3>
    <p>WYou understand that all postings, messages, text or other materials ("Content") posted on, transmitted through, or linked from the Service, are the sole responsibility of the person from whom such Content originated and should not necessarily be relied upon. This means that you, and not the owner(s) of Tradeescrow, are entirely responsible for all Content that you publish, display, post, email or otherwise make available and/or transmit via the Service. You understand that Tradeescrow does not control, and is not responsible for Content made available and/or transmitted through the Service, and that by using the Service, you may be exposed to Content that is inaccurate, misleading, or otherwise objectionable. Not only does Tradeescrow not control the content posted and transmitted via the Service, but the owner(s) of Tradeescrow also does not guarantee the accuracy, completeness, timeliness or usefulness of any information on the Service and neither adopts nor endorses nor is responsible for the accuracy or reliability of any opinion, advice, statement, representation or promise made. Furthermore, Tradeescrow site and Content available through the Service may contain links to other websites, which are completely independent of Tradeescrow and the owner(s) of Tradeescrow. Tradeescrow makes no representation or warranty as to the accuracy, completeness or authenticity of the information contained in any such site. Your linking to any other websites is at your own risk. You agree that you must evaluate, and bear all risks associated with, the use of any Content, that you may not rely on said Content, and that under no circumstances will the owner(s) of Tradeescrow be liable in any way for any Content or for any loss or damage of any kind incurred as a result of the use of any Content posted, emailed or otherwise made available and/or transmitted via the Service. You acknowledge that Tradeescrow does not pre-screen, pre-qualify or approve Content, but that Tradeescrow shall have the right (but not the obligation) in its sole discretion to refuse, delete or move any Content that is available via the Service, for violating the letter or spirit of the Terms and Conditions or the law or for any other reason..</p>
    <h3><span>3.</span> USER CONDUCT</h3>
    <p>You agree not to post, email, or otherwise make available Content: (a) that is unlawful, harmful, threatening, abusive, harassing, defamatory, pornographic, libellous, invasive of another's privacy, or harms minors in any way; (b) that harasses, degrades, intimidates or is hateful toward an individual or group of individuals on the basis of religion, gender, sexual orientation, race, ethnicity, age, or disability; (c) that impersonates any person or entity, including, but not limited to, a Tradeescrow employee, or falsely states or otherwise misrepresents your affiliation with a person or entity; (d) that includes personal or identifying information about another person without that person's explicit consent; (e) that is false, deceptive, misleading, deceitful, or constitutes "bait and switch"; (f) that infringes any patent, trademark, trade secret, copyright or other proprietary rights of any party, or Content that you do not have a right to make available under any law or under contractual or fiduciary relationships; (g) that constitutes or contains "affiliate marketing," "link referral code," "junk mail," "spam," "chain letters," "pyramid schemes," or unsolicited commercial advertisements; (h) that constitutes or contains any form of advertising or solicitation if posted in areas of Tradeescrow site which are not designated for such purposes; (i) that includes links to commercial services or websites, including but not limited to local market related services, except as allowed in "Tradeescrow ads"; (j) that advertises any illegal services or the sale of any items the sale of which is prohibited or restricted by applicable law, including without limitation items the sale of which is prohibited or regulated by the laws of any of the states or territories of South Africa; (k) that contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment (l) that disrupts the normal flow of dialogue with an excessive number of messages (flooding attack) to the Service, or that otherwise negatively affects other users' ability to use the Service, or; (m) that employs misleading email addresses, or forged headers or otherwise manipulated identifiers in order to disguise the origin of Content transmitted through the Service.</p>
    <p>With respect to other users of the Service, you also agree not to: (n) contact anyone who has asked not to be contacted; (o) "stalk" or otherwise harass anyone; (p) collect personal data about other users for commercial or unlawful purposes; (q) use automated means, including spiders, robots, crawlers, data mining tools, or the like to download data from the Service - exception is made for Internet search engines and non-commercial public archives that comply with our robots.txt file; (r) purposefully post Content in a irrelevant category or city, repeatedly post the same or similar Content or otherwise impose an unreasonable or disproportionately large load on our infrastructure, or; (s) attempt to gain unauthorized access to the Tradeescrow computer systems or engage in any activity that disrupts, diminishes the quality of, interferes with the performance of, or impairs the functionality of, the Service or Tradeescrow website.</p>
    
    <p>Tradeescrow maintains a zero tolerance "spam" policy. You understand and agree that sending unsolicited email advertisements to users of the Service or through the Service's computer systems, which is expressly prohibited by these Terms and Conditions, will use or cause to be used servers located in South Africa. Any unauthorized use of Tradeescrow computer systems is a violation of these Terms and Conditions and certain federal and state laws, including but not limited to the Computer Fraud and Abuse Act and sections of the various criminal and civil codes of the states, territories of South Africa. Such violations may subject the sender and his or her agents to criminal and/or civil criminal penalties. Tradeescrow expressly reserves the right to delete without notice any information posted by an individual who refuses to comply with any of the provisions contained herein.</p>
    
    
    <h3><span>4.</span> INTERACTIONS WITH OTHER USERS</h3>
    <p>Your interactions with individuals, organizations or companies found on or through the Service, including payment and delivery of services or goods, and any other terms, conditions, warranties or representations associated with such dealings, are solely between you and such individuals, organizations or companies. You agree that Tradeescrow shall not be responsible or liable for any loss or damage of any sort incurred as the result of any such dealings. If there is a dispute between participants on this Service, or between users and any third party, you understand and agree that the owner(s) of Tradeescrow is under no obligation to become involved. In the event that you have a dispute with one or more other users, you hereby release the owner(s) of Tradeescrow, its officers, employees, agents and successors in rights from claims, demands and damages (actual and consequential) of every kind or nature, known or unknown, suspected and unsuspected, disclosed and undisclosed, arising out of or in any way related to such disputes and/ or our Service. You understand and agree that Tradeescrow makes no representations whatsoever regarding its users, including but not limited to a user's personal character, behavioural and personality traits, competency as a motor vehicle operator, and physical and mental health and well being.</p>
    <h3><span>5.</span> PRIVACY POLICY AND INFORMATION DISCLOSURE</h3>
    <p>Tradeescrow has established a Privacy Policy to explain to users of the Tradeescrow website and the Service how their information is collected and used. Please read over this information carefully and use it to guide your decision-making with respect to your use of the Service. Your use of Tradeescrow website or the Service signifies acknowledgement of and agreement to our Terms and Conditions, of which this Privacy Policy is an important component.</p>
    <p>You acknowledge and agree that Tradeescrow may, in its sole discretion, preserve or disclose your Content, as well as your information, such as email addresses, IP addresses, timestamps, and other user information, if required to do so by law or in the good faith belief that such preservation or disclosure is reasonably necessary to: comply with legal process; enforce these Terms and Conditions; respond to claims that any Content violates the rights of third-parties; or protect the rights, property, or personal safety of Tradeescrow, its users and/or the general public. During your use of Tradeescrow Service, we may track certain information about your browsing patterns, including the URL that you just came from (including a URL not on our site), which URL you go to when you leave our site, what browser you are using and your IP address. This is a common practice and many websites routinely collect this information. Internally, Tradeescrow uses your information to improve our marketing and promotional efforts, to statistically analyse site usage, and to improve and customize the Service's functionality and offerings. We believe that this will enable us to better meet your needs. All postings on the Service and on Tradeescrow community forums are stored in our database, even after "deletion," and may be archived elsewhere. Our web logs and other records are stored indefinitely. Tradeescrow expressly reserves the right to use the information in our records to determine if users are using multiple usernames and to take any necessary corrective action. We will not sell or lease your personally identifiable information to third parties. When you post a message on Tradeescrow Service, you necessarily disclose identifiable information to third party users of the Service, as indicated above. This information is provided to allow other users to contact you.</p>
    <p>In addition, Tradeescrow will cooperate with all law enforcement and/or legal inquiries and with all third parties to enforce intellectual and other property rights. Such inquiries may include disclosure of your personally identifiable information. We can, and by use of the Service you authorize us to disclose any information about you to law enforcement and other government officials as we, in our sole discretion, believe necessary or appropriate. This Privacy Policy pertains solely to the use by and collection of information on the Service. These policies do not apply, and Tradeescrow has no control over any information you disclose to third parties, whether they are other users of the Service or third party advertisers adhering to their own distinct privacy policies. Tradeescrow, or people who post on Tradeescrow website or the Service, may provide links on Tradeescrow website or the Service to third party websites, which may have different privacy practices. We are not responsible for, nor have any control over, the privacy policies of those third party websites, and encourage all users to read the privacy policies of each and every website visited. Please exercise care before disclosing personal information to any third party.</p>
    
    <p>Due to the nature of the Internet, Tradeescrow can not guarantee that all of your private communications, or personally identifiable information may never be disclosed in ways not anticipated or discussed in this Privacy Policy, such as by a third party unlawfully intercepting or accessing a transmission. Thus, any information made available by you through the Service is done with your full understanding that Tradeescrow is in no way responsible for any possible invasions of your privacy which may result from said disclosures by you. Finally, Tradeescrow reserves the right to incorporate changes or modifications to this Privacy Policy, which shall be effective upon posting.</p>
    
    <h3><span>6.</span>  LIMITATIONS ON SERVICE</h3>
    <p>You acknowledge that Tradeescrow may establish limits concerning use of the Service, including the maximum number of days that Content will be retained by the Service, the maximum number and size of postings, email messages, or other Content that may be transmitted or stored by the Service, and the frequency with which you may access the Service. You agree that the owner(s) of Tradeescrow has no responsibility or liability for the deletion or failure to store any Content maintained or transmitted by the Service. You acknowledge that Tradeescrow reserves the right at any time to modify or discontinue the Service (or any part thereof) with or without notice, and that Tradeescrow shall not be liable to you or to any third party for any modification, suspension or discontinuance of the Service.</p>
    <h3><span>7.</span> TERMINATION OF SERVICE</h3>
    <p>You agree that Tradeescrow, in its sole discretion, has the right (but not the obligation) to delete or deactivate your account, block your email or IP address, or otherwise terminate your access to or use of the Service (or any part thereof), immediately and without notice, and remove and discard any Content within the Service, for any reason, including, without limitation, if Tradeescrow believes that you have acted inconsistently with the letter or spirit of the Terms and Conditions. Further, you agree that the owner(s) of Tradeescrow shall not be liable to you or any third-party for any termination of your access to the Service. Further, you agree not to attempt to use the Service after said termination. Sections 2, 4-5, 8-10 and 12 shall survive termination of these Terms and Conditions.</p>
    <h3><span>8.</span> PROPRIETARY RIGHTS</h3>
    <p>Tradeescrow owns and retains proprietary rights in the Service and Tradeescrow website. The Service and Tradeescrow website are protected to the fullest extent permitted by copyright laws and international treaties The Service and Tradeescrow website contain the copyrighted material, trademarks and other proprietary information of Tradeescrow and its licensors. Furthermore, Content displayed on or through the Service is protected by copyright as a collective work and/or compilation, pursuant to copyrights laws, and international conventions. Any reproduction, modification, creation of derivative works from or redistribution of the Sites or the collective work is prohibited. Copying or reproducing the sites or any portion thereof to any other server or location for further reproduction or redistribution is prohibited. You further agree not to reproduce, duplicate or copy Content from the Service, and agree to abide by any and all copyright notices displayed on the Service. You may not decompile or disassemble, reverse engineer or otherwise attempt to discover any source code contained in the Service. Without limiting the foregoing, you agree not to reproduce, duplicate, copy, sell, resell or exploit for any commercial purposes, any aspect of the Service.</p>
    <p>Although Tradeescrow does not claim ownership of content that its users post, by posting Content to any public area of the Service, you automatically grant, and you represent and warrant that you have the right to grant, to Tradeescrow an irrevocable, perpetual, non-exclusive, fully paid, worldwide license to use, copy, perform, display, and distribute said Content and to prepare derivative works of, or incorporate into other works, such Content, and to grant and authorize sublicenses (through multiple tiers) of the foregoing.</p>
    <h3><span>9.</span> DISCLAIMER OF WARRANTIES</h3>
    <p>YOU UNDERSTAND AND AGREE THAT USE OF Tradeescrow WEBSITE AND THE SERVICE IS ENTIRELY AT YOUR OWN RISK. Tradeescrow WEBSITE AND THE SERVICE ARE PROVIDED ON AN "AS IS" OR "AS AVAILABLE" BASIS, WITHOUT ANY WARRANTIES OF ANY KIND. ALL EXPRESS, IMPLIED, STATUTORY OR ANY OTHER WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT OF PROPRIETARY RIGHTS, ARE EXPRESSLY DISCLAIMED TO THE FULLEST EXTENT PERMITTED BY LAW. TO THE FULLEST EXTENT PERMITTED BY LAW, the owner(s) of Tradeescrow DISCLAIMS ANY WARRANTIES FOR THE SECURITY, RELIABILITY, TIMELINESS, ACCURACY, AND PERFORMANCE OF Tradeescrow WEBSITE AND THE SERVICE AND ASSUMES NO RESPONSIBILITY FOR THE RETENTION, DELETION, MISDELIVERY OR FAILURE TO STORE ANY USER COMMUNICATIONS AND SPECIFICALLY DOES NOT WARRANT THAT YOUR USE OF Tradeescrow WEBSITE OR THE SERVICE WILL BE SECURE, UNINTERRUPTED, ALWAYS AVAILABLE OR ERROR-FREE, OR WILL MEET YOUR REQUIREMENTS OR NEEDS, OR THAT ANY DEFECTS IN THE SERVICE WILL BE CORRECTED. TO THE FULLEST EXTENT PERMITTED BY LAW, Tradeescrow DISCLAIMS ANY WARRANTIES FOR OTHER SERVICES OR GOODS RECEIVED THROUGH OR ADVERTISED ON Tradeescrow SITE OR THE SERVICE, OR ACCESSED THROUGH ANY LINKS ON Tradeescrow WEBSITE. TO THE FULLEST EXTENT PERMITTED BY LAW, Tradeescrow DISCLAIMS ANY WARRANTIES FOR VIRUSES OR OTHER HARMFUL COMPONENTS IN CONNECTION WITH Tradeescrow SITE OR THE SERVICE.</p>
    <p>We recognize the privacy interests of children and encourage parents and guardians to take an active role in their children’s online activities and interests. Children under 13 (or under 16 in the European Economic Area) should not use the Services. If we learn that we’ve collected personal data from a child under those ages.</p>
    <h3><span>10.</span>  LIMITATIONS OF LIABILITY</h3>
    <p>UNDER NO CIRCUMSTANCES SHALL Tradeescrow BE LIABLE TO YOU OR ANY OTHER PERSON OTHER THAN YOU FOR DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES (EVEN IF Tradeescrow HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES), RESULTING FROM ANY ASPECT OF YOUR USE OF Tradeescrow WEBSITE OR THE SERVICE, WHETHER THE DAMAGES ARISE FROM USE OR MISUSE OF Tradeescrow OR THE SERVICE, FROM INABILITY TO USE Tradeescrow WEBSITE OR THE SERVICE, INCLUDING BUT NOT LIMITED TO COST OF PROCUREMENT OF SUBSTITUTE SERVICES OR SERVICE INTERRUPTIONS OR THE INTERRUPTION, SUSPENSION, MODIFICATION, ALTERATION, OR TERMINATION OF Tradeescrow WEBSITE OR THE SERVICE, INCLUDING BUT NOT LIMITED TO DAMAGES FOR LOSS OF DATA AND/OR LOSS OF PROGRAMS. SUCH LIMITATION SHALL ALSO APPLY WITH RESPECT TO DAMAGES INCURRED BY REASON OF OTHER SERVICES OR PRODUCTS RECEIVED THROUGH OR ADVERTISED IN CONNECTION WITH Tradeescrow WEBSITE OR THE SERVICE OR ANY LINKS ON Tradeescrow WEBSITE, AS WELL AS BY REASON OF ANY INFORMATION OR ADVICE RECEIVED THROUGH OR ADVERTISED IN CONNECTION WITH Tradeescrow WEBSITE OR THE SERVICE OR ANY LINKS ON Tradeescrow WEBSITE. THESE LIMITATIONS SHALL APPLY TO THE FULLEST EXTENT PERMITTED BY LAW. NOTWITHSTANDING ANYTHING TO THE CONTRARY CONTAINED HEREIN, the owner(s) of Tradeescrow LIABILITY TO YOU FOR ANY CAUSE WHATSOEVER, AND REGARDLESS OF THE FORM OF THE ACTION, WILL AT ALL TIMES BE LIMITED TO THE AMOUNT PAID, IF ANY, BY YOU TO Tradeescrow FOR THE SERVICE DURING THE TERM OF USE. IN ADDITION, Tradeescrow DISCLAIMS ALL LIABILITY, REGARDLESS OF THE FORM OF ACTION, FOR THE ACTS OR OMISSIONS OF OTHER USERS, INCLUDING UNAUTHORIZED USERS ("HACKERS") OF Tradeescrow WEBSITE OR THE SERVICE.</p>
    <h3><span>11.</span> STATE-BY-STATE VARIATIONS</h3>
    <p>Certain jurisdictions limit the applicability of warranty disclaimers and limitations of liability so the above disclaimers of warranty and limitations of liability may not apply to you.</p>
    <h3><span>12.</span>  GENERAL INFORMATION</h3>
    <p>The Terms and Conditions constitute the entire agreement between you and the owner(s) of Tradeescrow and govern your use of the Service, superseding any prior agreements between you and Tradeescrow. This Agreement is entered into in the country of South Africa. Accordingly, the Terms and Conditions and the relationship between you and Tradeescrow shall be governed by the laws of South Africa without regard to said state's conflict of law provisions. YOU ARE RESPONSIBLE FOR COMPLYING WITH YOUR OWN LOCAL LAWS, WHICH MAY VARY WITH RESPECT TO CERTAIN ACTIVITIES OR PEOPLE (e.g., MINORS). Since we make no warranties and have limited our liabilities, you should have little reason to have a grievance with us. Should you nevertheless bring legal action against us, you irrevocably agree that regardless of any statute or law to the contrary, it will be brought and maintained on an individual basis (and not consolidated with similar cases) within one (1) year after the claim arises or be barred. As disincentive for unwarranted litigation, you agree that if you sue us and don't win on the merits, you will pay our defence costs, including reasonable legal fees for in-house and outside counsel. If we are required to enforce this Agreement or our rights, you agree it is reasonable to send you legal notices and papers by electronic mail at your stated address (we would also attempt to send you a backup copy by regular mail). You and the owner(s) of Tradeescrow agree to submit to the personal and exclusive jurisdiction of the courts located within the country of South Africa. The failure of the owner(s) of Tradeescrow to exercise or enforce any right or provision of the Terms and Conditions shall not constitute a waiver of such right or provision. If any provision of the Terms and Conditions is found by a court of competent jurisdiction to be invalid, the parties nevertheless agree that the court should endeavour to give effect to the parties' intentions as reflected in the provision, and the other provisions of the Terms and Conditions remain in full force and effect. You agree that regardless of any statute or law to the contrary, any claim or cause of action arising out of or related to use of the Service or the Terms and Conditions must be filed within one (1) year after such claim or cause of action arose or be forever barred.</p>
    <h3><span></span>Disclaimer</h3>
    <p>The information contained in this website is for general information purposes only. The information is provided by Tradeescrow and while we endeavour to keep the information up to date and correct, we make no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, suitability or availability with respect to the website or the information, products, services, or related graphics contained on the website for any purpose. Any reliance you place on such information is therefore strictly at your own risk.</p>
    <p>
    In no event will we be liable for any loss or damage including without limitation, indirect or consequential loss or damage, or any loss or damage whatsoever arising from loss of data or profits arising out of, or in connection with, the use of this website.</p>
    <p>
    Through this website you are able to link to or view information provided by other websites which are not under the control of Tradeescrow. We have no control over the nature, content and availability of those sites. The inclusion of any links, maps or driving directions does not necessarily imply a recommendation or endorse the views expressed within them.</p>
    <p>
    Every effort is made to keep the website up and running smoothly. However, Tradeescrow takes no responsibility for, and will not be liable for, the website being temporarily unavailable due to technical issues beyond our control.</p>
    </div>
    </div>
    </div>
    
@include('user.footerh')